### ISSUE TITLE
"occurs_in" should autocomplete to cellular anatomical entity not CC

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-form#110]
A bug found by @goodb 

autocomplete in the form allows for things to 'occur in' protein complexes which is incorrect according to the schema
It should should be looking for children of cellular anatomical entity, not cellular component.

This bug is also in the graph edit @kltm 

@vanaukenk 

thanks @goodb

**Comment by kltm** [comment]
@tmushayahama To clarfty, is this an issue in the Noctua GOlr load or in the term used to pin/filter the results from the Noctua GOlr load (or something else)?

**Comment by vanaukenk** [comment]
@tmushayahama 
Yes, we hadn't updated this behavior in Noctua yet, but this was a known issue.

**Comment by vanaukenk** [comment]
Notes from 2020-07-22 workbenches call:

The desired behavior for Noctua is to allow MFs and BPs to occur in anatomical entities (CARO:0000000), which includes cellular anatomical entities (GO:0110165), but NOT to occur in protein-containing complexes (GO:0032991).

However, I think we also still need to include CC terms that are not descended from 'cellular anatomical entity' and also not protein-containing complexes, e.g. virion part and its children.

@tmushayahama - let me know if you have any questions about this.

**Comment by goodb** [comment]
@vanaukenk we need specific guidance here for the edge cases like virion part.  Ideally we would have one root term per autocompletable field...

**Comment by vanaukenk** [comment]
@goodb 

If we would like to have only one root term per autocomplete field, then we may have to go the route of allowing all of GO CC in the CC field of Noctua, but educating curators about what values they are supposed to select.  

We've had some discussions about what to do with virion and virion part in GO CC, but it's not been resolved (similar to protein-containing complexes), so may just have to opt for a pragmatic solution, i.e. more inclusive autocomplete and curator education, to get what we want for GO-CAMs.

Happy to discuss further with you, though, if you have other suggestions.  Thx.

**Comment by goodb** [comment]
@vanaukenk I think the form should be a direct reflection of the schema.  If it is not possible to do that, then we have a problem with the ontology that should be dealt with there at that point rather than kicking it down the road.  Not solving the ontology problem just creates more work for the software team now (hacky workarounds) or for everyone later (bad models that need fixing).  

For this field we have
```
occurs_in: @<AnatomicalEntity> {0,1};
```
Where AnatomicalEntity is any subclass of http://purl.obolibrary.org/obo/CARO_0000000 
I suggest that it must be possible to identify an appropriate grouping class that subsumes any potential location for a molecular activity.  If the definition of CARO anatomical entity is too strict, then lets either go up to its parent 'biological entity' or introduce another appropriate class that can group all the locations of the activities.

**Comment by vanaukenk** [comment]
@goodb 

Yes, I think we'll need to look at CARO again, as I'm not even sure that 'biological entity' fully works for viral CCs.

**Comment by vanaukenk** [comment]
The form is working as desired, so closing this ticket.
