### ISSUE TITLE
Further constrain MF occurs_in CC values

### ISSUE THREAD

**Issue by vanaukenk** [geneontology/noctua-form#134]
For the Create Activity Unit version of the form, we need to further constrain the CC values in which an MF can occur to:

MF occurs_in cellular anatomical entity (GO:0110165) OR root cellular component (GO:0005575)

This will prevent curators from saying that an MF occurs_in a protein-containing complex (GO:0032991); they must use the CC annotation version of the form to make those statements.

Note that we still have to sort out the virion terms wrt the form.

**Comment by tmushayahama** [comment]
@ukemi @vanaukenk it seems the above of just adding isa_closure cellular anatomical entity will exclude Virion. Alternatively, maybe this can work for now. Lemme know?

MF occurs  in (CC **OR NOT** Protein Containing Complex ) so that virion component can be searched

to the interested, @lpalbou @kltm @cmungall will this GOlr request work as I think it will work, so far seems to retrieve.. 
![image](https://user-images.githubusercontent.com/2273929/123717483-cda3e700-d831-11eb-85b9-d7a77a9e9d53.png)

**Comment by ukemi** [comment]
Can we do NOT in the Shex or an owl representation though?

**Comment by tmushayahama** [comment]
@ukemi it better be there :) . I believe SHex will have a negate ShapeNOT somewhere. tagging @balhoff . Having RootCC but not all it's closures (not PCComplex) cannot be defined as RootCC or Virion or Anatomical otherwise RootCC Shape will take precedence.

But I think this is an XY problem and really PC Complex should be removed from CC closure.

**Comment by tmushayahama** [comment]
@vanaukenk I think this is done and on production
