### ISSUE TITLE
bug in noctura form for CC annotation?

### ISSUE THREAD

**Issue by LiNiMGI** [geneontology/noctua-form#222]
@tmushayahama @vanaukenk 
seems to me that after the Noctua maintenance outage on May 25th, noctua form for CC annotation changed:
when click the "+" sign on the right of the gene product, there are 7 options curators can chose to enter the data, but: no located in CC available.

I am also not sure: do we really want to put the 7 options there? 

thank for the help,
Li

**Comment by suzialeksander** [comment]
![image](https://github.com/geneontology/noctua-form/assets/13735608/4f3bc9f8-18ff-4de3-b671-66e81b57db1f)
Thanks for reporting this @LiNiMGI 

To add, it seems I can't make some "standard annotations"- if I select located_in (since is_active_in is disabled), there's no option to annotate to GO:0005737; options in the drop-down include XAO:0005039 or dendrite cytoplasm.

**Comment by krchristie** [comment]
This pull-down menu in the BP form is also similarly affected.

![20230530-NoctuaForm-extensionPulldown](https://github.com/geneontology/noctua-form/assets/10533218/eb1db62b-3e87-4db7-9d2a-12319726e532)

**Comment by vanaukenk** [comment]
We discussed this on the Noctua workbenches call.

@balhoff is it possible that this issue is related to replacing CARO with UBERON?

In the ShEx we have:

PREFIX GoAnatomicalEntity: <http://purl.obolibrary.org/obo/CARO_0000000>

but if that CARO term is no longer being used, then perhaps that's why we've 'lost' some GO CC terms in Noctua?

I can update the ShEx with the appropriate UBERON term, if necessary.

**Comment by balhoff** [comment]
@vanaukenk I didn't think that change had propagated out to places that would affect this yet. But it's possible! It seems high priority for me to find and update references to CARO throughout all of GO.

**Comment by balhoff** [comment]
This should be fixed by the next GO snapshot and subsequent refresh of the ontologies used by Noctua.

**Comment by LiNiMGI** [comment]
@vanaukenk @tmushayahama 
What’s the status on fixing this bug in the form? This bug makes both the CC and the BP forms essentially unusable for MGI.

At our weekly GO meeting, David@ukemi said that fixing this would be part of the project on extensions. If the extensions project is going to take a long time, is there any possibility to rollback the changes that created this problem in Noctua production and move the extensions project to Noctua Dev, so that we can use the form to make our annotations again? 

Thanks!

**Comment by vanaukenk** [comment]
@LiNiMGI   I'm sorry this bug caused such havoc.
My understanding, though, is that this was an [ontology issue](https://github.com/geneontology/go-ontology/issues/25481), so we don't need to rollback any Noctua code.

@kltm - do you think we could try a neo update to see if that fixes this problem?  Thank you.

**Comment by vanaukenk** [comment]
Okay - late-breaking Friday update :-)

The ontology fix that @balhoff and @pgaudet put in DID fix the problem.

There was some confusion, though, because the word 'Anatomy' underneath relations like 'located in' was taken to mean something other than GO CC.  I think this is a case where perhaps too much of the underlying data model gets exposed in the tool and we should think about updating the UI to make things clearer.

So @kltm - no need to update neo and apologies for the false alarm.

**Comment by vanaukenk** [comment]
I also just double-checked in the BP only form and this is working okay there, too.

@LiNiMGI @krchristie - if you encounter any other issues, please reopen this ticket.  Thx.

**Comment by tmushayahama** [comment]
@vanaukenk @LiNiMGI @kltm I was looking at the previous version of NF and the question above, the only difference was words located in CC to located in Anatomy. Reading carefully what @LiNiMGI said "**7 options** curators can chose to enter the data, but: **no located in CC available**." I counted 7 options from the screenshot, SO I can conclude, I am suspecting it is the word Anatomy which might be confusing as per @krchristie comment https://github.com/geneontology/noctua-form/issues/223
located in CC is now located in Anatomy. Thanks @krchristie @LiNiMGI 
Very sorry for the confusion
