### ISSUE TITLE
Handle Cardinality of One to Many on table display

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/noctua-form#80]
From https://github.com/geneontology/noctua-form/issues/66 table is duplicating values if the predicate cardinality is more than one. i.e many has_inputs or has outputs

**Comment by vanaukenk** [comment]
@tmushayahama 
It looks like entry of multiple 'has input'/'has output' is working now on the form, but there is  a problem here with the evidence on the molecular function annotation - it's fine on the form, because I can save, but it doesn't display properly in the table:

![image](https://user-images.githubusercontent.com/1730534/79614015-a39f5280-80cd-11ea-831d-6a2940b0ca3f.png)

**Comment by vanaukenk** [comment]
This looks to be working fine now on noctua-dev:

![image](https://user-images.githubusercontent.com/1730534/80109178-2ea79f00-854b-11ea-959e-3b9e515b9b9a.png)


Thank you!

**Comment by vanaukenk** [comment]
Done
